// Generated by scripts/migration-checksums.mjs. Do not edit.
import type { MigrationSourceDefinition } from "./types";

export const MIGRATION_CHECKSUMS: Readonly<Record<string, string>> =
  Object.freeze({
  });

export const MIGRATION_SOURCE_DEFINITIONS: readonly MigrationSourceDefinition[] =
  Object.freeze([
  ]);
