// Generated by scripts/migration-checksums.mjs. Do not edit.
import type { MigrationSourceDefinition } from "./types";
import { migration as migrationSource0 } from "./versions/20260911_001_inventory-registration-profile";

export const MIGRATION_CHECKSUMS: Readonly<Record<string, string>> =
  Object.freeze({
  "20260911_001_inventory-registration-profile": "28122c7ef015cc679e2f546ef1a93e22be267c8e4a94091d6679e97030560bcd",
  });

export const MIGRATION_SOURCE_DEFINITIONS: readonly MigrationSourceDefinition[] =
  Object.freeze([
  migrationSource0,
  ]);
