import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { iso31661, iso31662 } from "iso-3166";

const require = createRequire(import.meta.url);
const packageMetadata = JSON.parse(
  await readFile(require.resolve("iso-3166/package.json"), "utf8"),
);
const outputPath = fileURLToPath(
  new URL("../time/iso3166Codes.ts", import.meta.url),
);
const optionsOutputPath = fileURLToPath(
  new URL("../time/iso3166Options.ts", import.meta.url),
);

const countryCodes = [...new Set(iso31661.map((entry) => entry.alpha2))].sort();
const subdivisionCodes = [
  ...new Set(iso31662.map((entry) => entry.code)),
].sort();
const countryOptions = iso31661
  .map(({ alpha2: code, name }) => ({ code, name }))
  .sort((left, right) =>
    left.name.localeCompare(right.name, "en") || left.code.localeCompare(right.code),
  );
const subdivisionOptions = iso31662
  .map(({ code, name }) => ({ code, countryCode: code.split("-")[0], name }))
  .sort((left, right) =>
    left.countryCode.localeCompare(right.countryCode) ||
    left.name.localeCompare(right.name, "en") ||
    left.code.localeCompare(right.code),
  );

if (countryCodes.length !== 249) {
  throw new Error(
    `Expected 249 assigned country codes, found ${countryCodes.length}`,
  );
}

const formatRows = (values, perRow) =>
  Array.from({ length: Math.ceil(values.length / perRow) }, (_, index) =>
    `  ${values
      .slice(index * perRow, (index + 1) * perRow)
      .map((value) => JSON.stringify(value))
      .join(", ")},`,
  ).join("\n");

const formatObjects = (values) =>
  values.map((value) => `  ${JSON.stringify(value)},`).join("\n");

const generated = `// Generated by scripts/generateIso3166Codes.mjs from the MIT-licensed
// iso-3166 package v${packageMetadata.version} (https://github.com/wooorm/iso-3166).
// Run \`npm run generate:iso-codes --workspace=@atcloud/shared-time\` to refresh.

export const ISO_3166_DATASET_VERSION = ${JSON.stringify(packageMetadata.version)};

export const ISO_COUNTRY_CODES = [
${formatRows(countryCodes, 10)}
] as const;

export const ISO_SUBDIVISION_CODES: readonly string[] = [
${formatRows(subdivisionCodes, 8)}
];
`;

const generatedOptions = `// Generated by scripts/generateIso3166Codes.mjs from the MIT-licensed
// iso-3166 package v${packageMetadata.version} (https://github.com/wooorm/iso-3166).
// Run \`npm run generate:iso-codes --workspace=@atcloud/shared-time\` to refresh.

export interface IsoCountryOption {
  code: string;
  name: string;
}

export interface IsoSubdivisionOption {
  code: string;
  countryCode: string;
  name: string;
}

export const ISO_COUNTRY_OPTIONS: readonly IsoCountryOption[] = [
${formatObjects(countryOptions)}
];

export const ISO_SUBDIVISION_OPTIONS: readonly IsoSubdivisionOption[] = [
${formatObjects(subdivisionOptions)}
];
`;

if (process.argv.includes("--check")) {
  const [currentCodes, currentOptions] = await Promise.all([
    readFile(outputPath, "utf8").catch(() => ""),
    readFile(optionsOutputPath, "utf8").catch(() => ""),
  ]);
  if (currentCodes !== generated || currentOptions !== generatedOptions) {
    throw new Error("Generated ISO 3166 data is out of date");
  }
} else {
  await Promise.all([
    writeFile(outputPath, generated),
    writeFile(optionsOutputPath, generatedOptions),
  ]);
}
