import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { iso31661, iso31662 } from "iso-3166";

const require = createRequire(import.meta.url);
const packageMetadata = JSON.parse(
  await readFile(require.resolve("iso-3166/package.json"), "utf8"),
);
const outputPath = fileURLToPath(
  new URL("../time/iso3166Codes.ts", import.meta.url),
);

const countryCodes = [...new Set(iso31661.map((entry) => entry.alpha2))].sort();
const subdivisionCodes = [
  ...new Set(iso31662.map((entry) => entry.code)),
].sort();

if (countryCodes.length !== 249) {
  throw new Error(
    `Expected 249 assigned country codes, found ${countryCodes.length}`,
  );
}

const formatRows = (values, perRow) =>
  Array.from({ length: Math.ceil(values.length / perRow) }, (_, index) =>
    `  ${values
      .slice(index * perRow, (index + 1) * perRow)
      .map((value) => JSON.stringify(value))
      .join(", ")},`,
  ).join("\n");

const generated = `// Generated by scripts/generateIso3166Codes.mjs from the MIT-licensed
// iso-3166 package v${packageMetadata.version} (https://github.com/wooorm/iso-3166).
// Run \`npm run generate:iso-codes --workspace=@atcloud/shared-time\` to refresh.

export const ISO_3166_DATASET_VERSION = ${JSON.stringify(packageMetadata.version)};

export const ISO_COUNTRY_CODES = [
${formatRows(countryCodes, 10)}
] as const;

export const ISO_SUBDIVISION_CODES: readonly string[] = [
${formatRows(subdivisionCodes, 8)}
];
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error("Generated ISO 3166 codes are out of date");
  }
} else {
  await writeFile(outputPath, generated);
}
